lstVague = (
    "a large number",
    "a lot",
    "few",
    "many",
    "most",
    "numerous",
    "some",
    "really",
    "several",
    "often",
    "very",
    "quite",
)


lstShouts = (
    "ah",
    "aha",
    "alas",
    "aw",
    "ay",
    "bah",
    "eh",
    "hurray",
    "oh",
    "oho",
    "oh-oh",
    "ooh",
    "oops",
    "ow",
    "oy",
    "phew",
    "ugh",
    "uh",
    "woah",
    "wow",
    "yay",
    "yow",
)


lstAcronyms = [
    "AC",
    "ACM",
    "CPU",
    "DDR",
    "FPGA",
    "FSM",
    "GNU",
    "GPS",
    "GUI",
    "HF",
    "HTML",
    "IEEE",
    "LED",
    "OS",
    "PC",
    "PCB",
    "PDF",
    "USB",
    "RAM",
    "RF",
    "ROM",
    "VR",
    "URL",
    "WIFI",
]


tabShortForms = [
    (r"\w+(n\'t)", "not"),
    (r"\w+(\'re)", "are"),
    (r"\w+(\'ve)", "have"),
    (r"\w+(\'ll)", "will"),
]


tabNumbers = [
    ("0", "zero"),
    ("1", "one"),
    ("2", "two"),
    ("3", "three"),
    ("4", "four"),
    ("5", "five"),
    ("6", "six"),
    ("7", "seven"),
    ("8", "eight"),
    ("9", "nine"),
    ("10", "ten"),
    ("11", "eleven"),
    ("12", "twelfe"),
]


tabRedundantPhrases = [
    ("all of the", "all"),
    ("all in all", "overall"),
    ("approximately about", "about"),
    ("[Aa]t the moment", "currently"),
    ("[Aa]s a matter of fact", "in fact"),
    ("and so on", "etc."),
    ("by means of", "by"),
    ("but however", "however"),
    ("but nevertheless", "nevertheless"),
    ("close proximity", "proximity"),
    ("combined together", "combined"),
    ("despite of", "despite"),
    ("despite the fact that", "although"),
    ("DNS server", "DNS"),
    ("due to the fact that", "because"),
    ("end result", "result"),
    ("(?:exact same|exactly the same)", "same"),
    ("[Ff]or the most part", ""),
    ("[Ff]or the purpose of", "to"),
    ("(?:have|has) the ability to", "can"),
    ("HIV virus", "HIV"),
    ("in the case that", "in case"),
    ("in terms of", "in"),
    ("in order to", "to"),
    ("it is clear", ""),
    ("it seems that", ""),
    ("in the process of", ""),
    ("irregardless", "regardless"),
    ("LCD display", "LCD"),
    ("malicious attacks?", "attack"),
    ("more and more", "more"),
    ("not able", "unable"),
    ("not certain", "uncertain"),
    ("not many", "few"),
    ("not the same", "different"),
    ("(?:make|made) a decision about", "decide on"),
    ("[Oo]n the occasion of", "when"),
    ("[Oo]n the (?:one|other) hand", ""),
    ("of any of", "of"),
    ("originally discovered", "discovered"),
    ("over the time", "over time"),
    ("period (?:of|in) time", "period"),
    ("PIN number", "PIN"),
    ("reason why", "reason"),
    ("so therefore", "therefore"),
    ("(?:sufficient|adequate) enough", "sufficient"),
    ("that exists", ""),
    ("(?:a|the) type of", ""),
    ("USB bus", "USB"),
    ("whether or not", "whether"),
]


tabWrongCombinations = [
    ("could of", "could have"),
    ("de-factor", "de-facto"),
    ("last change", "last chance"),
    ("insure that", "ensure that"),
    ("must to", "must"),
    ("network package", "network packet"),
    ("object orientated", "object oriented"),
    ("time point", "point in time"),
    ("software packet", "software package"),
    ("thread model", "threat model"),
    ("(?:some|certain) extend", "extent"),
    (r"resource[- ]constraint", "resource-constrained"),
]


tabConfusedVerbNoun = [
    ("affect", "effect"),
    ("ascend", "ascent"),
    ("build", "built"),
    ("constrain", "constraint"),
    ("descend", "descent"),
    ("reverse", "inverse"),
    ("live", "life"),
    ("practice", "practise"),
    ("prove", "proof"),
    ("set up", "setup"),
    ("save", "safe"),
    ("shut down", "shutdown"),
    ("descent", "descend"),
]


tabSynonyms = [
    ("show", "illustrate", "demonstrate"),
    ("calculate", "determine"),
    ("analyze", "evaluate", "investigate"),
    ("precise", "concise"),
]


## Non Scientific / Informal
## ===================================================

tabNonScientificVerbs = [
    ("adept", "adapt"),
    ("adopt", "adapt"),
    ("compere", "compare"),
    ("exorcise", "exercise"),
    ("defuse", "diffuse"),
    ("sing", "sign"),
]

tabNonScientificWords = [
    ("altar", "alter"),
    ("airs", "air"),
    ("angel", "angle"),
    ("ass", "as"),
    ("avid", "avoid"),
    ("awl", "all"),
    ("bale", "able"),
    ("ballet", "ballot"),
    ("bellow", "below"),
    ("bite", "byte"),
    ("bloc", "block"),
    ("blocs", "blocks"),
    ("butt", "but"),
    ("botch", "both"),
    ("bloody", "blood"),
    ("boar", "board"),
    ("bough", "bought"),
    ("breach", "breech"),
    ("breaches", "breeches"),
    ("bye", "by"),
    ("cashed", "cached"),
    ("canvass", "canvas"),
    ("coarse", "course"),
    ("curse", "course"),
    ("compliment", "complement"),
    ("collar", "caller"),
    ("corral", "coral"),
    ("cor", "core"),
    ("cousin", "cosine"),
    ("fir", "for"),
    ("fur", "for"),
    ("foe", "for"),
    ("fife", "five"),
    ("fist", "first"),
    ("fuck", ""),
    ("damn", "dam"),
    ("discreet", "discrete"),
    ("desert", ""),
    ("dessert", ""),
    ("duel", "dual"),
    ("goof", "good"),
    ("ether", "either"),
    ("ere", "here"),
    ("heir", "here"),
    ("hew", "he"),
    ("hight", "height"),
    ("juts", "just"),
    ("jib", "job"),
    ("kelp", "help"),
    ("kid", "kit"),
    ("knot", "not"),
    ("loch", "lock"),
    ("massage", "message"),
    ("minuet", "minute"),
    ("mist", "must"),
    ("mowed", "mode"),
    ("mow", "now"),
    ("nit", "not"),
    ("ore", "or"),
    ("palate", "palette"),
    ("par", "part"),
    ("peace", "piece"),  # evil entry
    ("peek", "peak"),
    ("planing", "planning"),
    ("poop", "pop"),
    ("principal", "principle"),
    ("pubic", "public"),
    ("stationery", "stationary"),
    ("realty", "reality"),
    ("rite", "write"),
    ("rise", "raise"),
    ("sad", "said"),
    ("sate", "state"),
    ("seams", "seems"),
    ("shit", "shift"),
    ("sleight", "slight"),
    ("slut", "slot"),
    ("sire", "sure"),
    ("sow", "show"),
    ("sown", "shown"),
    ("stale", "stable"),
    ("steal", "steel"),
    ("steak", "stake"),
    ("temper", "tamper"),
    ("testes", "tests"),
    ("theses", "these"),
    ("thou", "you"),
    ("thee", "you"),
    ("thy", "your"),
    ("thine", "your"),
    ("untrue", "false"),
    ("vicious", "viscous"),
    ("wand", "want"),
    ("wend", "went"),
    ("wax", "way"),
    ("woks?", "work"),
    ("widow", "window"),
    ("witch", "which"),
    ("wildly", "widely"),
    ("withing", "within"),
    ("whore", "wore"),
    ("wring", "wrong"),
    ("writ", "write"),
    ("wright", "right"),
    ("ye", "you"),
]


tabInformalWords = [
    ("Also,?", "Furthermore,"),
    ("[Aa]nyways?", "nevertheless"),
    ("a couple of", "several"),
    ("a bit", "slightly"),
    ("a little bit", "slightly"),
    # ('about '+reNum, 'approximately'),
    ("all right", "acceptable"),
    ("bad", "negative"),
    ("big", "major"),
    ("do away", "remove"),
    ("bug", "fault"),
    ("buyer", "purchaser"),
    ("to know (?:an?|the|this)", "obtain"),
    ("But,?", "However,"),
    ("cheap", "inexpensive"),
    ("classical", "conventional"),
    ("cool", "great"),
    ("cute", "great"),
    ("deal with", "manage"),
    ("decent", "proper"),
    ("easy", "simple"),
    ("enough", "sufficient"),
    ("fat", "heavy"),
    ("good", "positive"),
    ("kinds", "types"),
    ("kind of", "rather"),
    ("like(?! to)", "such as"),
    ("sort of", "rather"),
    ("heaps of", "many"),
    ("huge", "large"),
    ("nice", "attractive"),
    ("normal", "general"),  # conventional
    ("places?", "location"),
    ("plenty", "many"),
    ("pretty", "rather"),
    ("rotations", "evolutions"),
    ("so", "Therefore,"),
    ("speed", "velocity"),
    ("silly", "inappropriate"),
    ("stuff", "things"),
    ("stupid", "inappropriate"),
    # ('then', 'subsequently'),
    ("things?", "object"),
    ("though", "although"),
    ("wonderful", "great"),
    ("quite", "rather"),
    ("whole", "entire"),
    # ('wrong', 'incorrect'),
    ("Well,?", ""),
    ("[Yy]ou", "one"),
    ("[Yy]our", "one's"),
]


tabBritishAmerican = [
    ("aeroplane", "airplane"),
    ("aluminium", "aluminum"),
    ("analyse", "analyze"),
    ("analogue", "analog"),
    ("catalogue", "catalog"),
    ("defence", "defense"),
    ("licence", "license"),
    ("centre", "center"),
    ("fibre", "fiber"),
    ("behaviour", "behavior"),
    ("colour", "color"),
    ("flavour", "flavor"),
    # (r'\w\wl')
]


################################################################################################


tabInformalVerbs = [
    ("admire", ""),
    ("amuse", ""),
    ("annoy", ""),
    ("ask", "request"),
    ("asked", "requested"),
    ("bake", ""),
    ("bang", ""),
    ("blush", ""),
    ("buy", "purchase"),
    ("bought", "purchased"),
    ("comes? back", "return"),
    ("check", "test"),
    ("cut down", "reduce"),
    ("(?:get|got) rid of", "eliminate"),
    ("got", "obtain"),
    ("go", ""),
    ("give", "provide"),
    ("guess", "estimate"),
    ("happen", "occur"),
    ("help(?:s|ed|ing)? out", "assist"),
    ("keep", "preserve"),
    ("let", "permit"),
    ("look", "observe"),
    # ('make', 'render'),
    ("mess", ""),
    ("pick(?:s|ed|ing)? up ", "collect"),
    ("put", ""),
    ("put together", "assembled"),
    ("points? out", "indicate"),
    ("see", "observe"),
    ("seems?", "appear"),
    ("seemed", "appeared"),
    ("speed(?:s|ed|ing)? up", "accelerate"),
    ("stay", "remain"),
    ("think about", "consider"),
    ("to be", ""),  # true?
    ("want", ""),
    ("wipe(?:s|d)? out", "eliminate"),
    ("[Ww]e got", "we obtain"),
]


informalVerbs = [
    "back",
    "bathe",
    "bare",
    "beg",
    "bless",
    "blot",
    "boast",
    "bore",
    "bruise",
    "bubble",
    "cheer",
    "chew",
    "comb",
    "cough",
    "cry",
    "dam",
    "dare",
    "drum",
    "dust",
    "embarrass",
    "fancy",
    "flower",
    "gaze",
    "grease",
    "groan",
    "harass",
    "hug",
    "itch",
    "jail",
    "jam",
    "jog",
    "juggle",
    "kiss",
    "like",
    "laugh",
    "love",
    "marry",
    "meddle",
    "mend",
    "mess",
    "moan",
    "mourn",
    "nail",
    "nod",
    "paddle",
    "pat",
    "peck",
    "pine",
    "poke",
    "pray",
    "preach",
    "prick",
    "rhyme",
    "rob",
    "rot",
    "shiver",
    "soothe",
    "scold",
    "scorch",
    "scribble",
    "shave",
    "shrug",
    "sigh",
    "sin",
    "ski",
    "smile",
    "sneeze",
    "snore",
    "squeak",
    "squeal",
    "stuff",
    "tame",
    "tremble",
    "trot",
    "tug",
    "tumble",
    "untidy",
    "wail",
    "whine",
    "whip",
    "wobble",
    "yawn",
    "yell",
]


tabInformalAdjectives = [
    ("apt", "appropriate"),
    ("austere", "strict"),
    ("awesome", "great"),
    ("awful", "negative"),
    ("awkward", "negative"),
    ("babyish", ""),
    ("baggy", ""),
    ("barren", "unproductive"),
    ("bogus", " counterfeit"),
    ("bony", ""),
    ("bossy", ""),
    ("bubbly", ""),
    ("bulky", "large"),
    ("bumpy", ""),
    ("cheery", ""),
    ("chubby", ""),
    ("colossal", "large"),
    ("crazy", ""),
    ("creepy", ""),
    ("cuddly", ""),
    ("cumbersome", "attractive"),
    ("cute", "attractive"),
    ("dear", ""),
    ("drab", ""),
    ("drafty", ""),
    ("dreary", ""),
    ("droopy", ""),
    ("dull", "tedious"),
    ("evil", "bad"),
    ("feisty", "spirited"),
    ("fickle", "vacillating"),
    ("filthy", "polluted"),
    ("firm", "inflexible"),
    ("flaky", "inflexible"),
    ("flashy", ""),
    ("flimsy", ""),
    ("flippant", ""),
    ("fluffy", ""),
    ("fond", "affectionate"),
    ("foolish", ""),
    ("frank", "honest"),
    ("frilly", ""),
    ("frizzy", ""),
    ("funny", "humorous"),
    ("fussy", "meticulous"),
    ("giant", "large"),
    ("giddy", ""),
    ("gloomy", "dark"),
    ("glum", "depressed"),
    ("grave", "serious"),
    ("grim", "hopeless"),
    ("gross", "large"),
    ("grouchy", "complaining"),
    ("grumpy", "angry"),
    ("happy", ""),
    ("hasty", "abrupt"),
    ("hearty", ""),
    ("heavenly", ""),
    ("hefty", "large"),
    ("hoarse", ""),
    ("husky", "deep"),
    ("icky", "disgusting"),
    ("impish", ""),
    ("intent", "determined"),
    ("jaunty", ""),
    ("jolly", ""),
    ("klutzy", ""),
    ("knobby", ""),
    ("knotty", ""),
    ("kooky", ""),
    ("lanky", ""),
    ("lavish", ""),
    ("lazy", "slow"),
    ("lovely", "attractive"),
    ("lucky", ""),
    ("lumpy", ""),
    ("mad", "bad"),
    ("merry", "good"),
    ("measly", ""),
    ("meaty", ""),
    ("mediocre", ""),
    ("meek", ""),
    ("mellow", ""),
    ("messy", ""),
    ("minty", ""),
    ("miserly", ""),
    ("misty", ""),
    ("muddy", ""),
    ("murky", ""),
    ("mushy", ""),
    ("nasty", "negative"),
    ("naughty", "negative"),
    ("neat", "attractive"),
    ("needy", ""),
    ("nice", "attractive"),
    ("nifty", ""),
    ("nimble", ""),
    ("nippy", ""),
    ("nutty", ""),
    ("obese", "corpulent"),
    ("ornery", ""),
    ("ornate", ""),
    ("paltry", "insignificant"),
    ("peppery", ""),
    ("perky", ""),
    ("pesky", ""),
    ("petty", "trivial"),
    ("plump", ""),
    ("plush", "luxurious"),
    ("portly", "corpulent"),
    ("posh", "luxurious"),
    ("pretty", "attractive"),
    ("prickly", ""),
    ("pristine", "clean"),
    ("prudent", ""),
    ("proud", ""),
    ("pungent", ""),
    ("puny", "small"),
    ("pushy", ""),
    ("putrid", ""),
    ("quaint", ""),
    ("queasy", ""),
    ("quirky", ""),
    ("rash", ""),
    ("regal", ""),
    ("repentant", ""),
    ("ripe", ""),
    ("rotten", ""),
    ("rowdy", ""),
    ("ruddy", ""),
    ("runny", ""),
    ("rusty", ""),
    ("sad", ""),
    ("scaly", ""),
    ("scarce", "limited"),
    ("scary", ""),
    ("scratchy", ""),
    ("scrawny", ""),
    ("serene", ""),
    ("shabby", ""),
    ("shadowy", ""),
    ("shady", ""),
    ("shiny", ""),
    ("shoddy", ""),
    ("showy", ""),
    ("shrill", ""),
    ("shy", ""),
    ("silly", "negative"),
    ("skinny", ""),
    ("sleepy", ""),
    ("slushy", ""),
    ("smoggy", ""),
    ("smug", ""),
    ("snappy", ""),
    ("sneaky", ""),
    ("snoopy", ""),
    ("soggy", ""),
    ("somber", ""),
    ("soupy", ""),
    ("speedy", ""),
    ("spicy", ""),
    ("spiffy", ""),
    ("spry", "agile"),
    ("squeaky", ""),
    ("squiggly", ""),
    ("stale", ""),
    ("starchy", ""),
    ("starry", ""),
    ("stingy", ""),
    ("stormy", ""),
    ("strident", ""),
    ("stupid", ""),
    ("stylish", ""),
    ("sugary", ""),
    ("sunny", ""),
    ("svelte", ""),
    ("sweaty", ""),
    ("sweet", ""),
    ("swift", "abrupt"),
    ("tame", ""),
    ("tan", ""),
    ("tart", "bitter"),
    ("tasty", ""),
    ("taut", "tense"),
    ("tender", "fragile"),
    ("tepid", ""),
    ("testy", ""),
    ("thirsty", ""),
    ("thorny", ""),
    ("thrifty", ""),
    ("tidy", ""),
    ("timely", ""),
    ("torn", ""),
    ("trusty", ""),
    ("tubby", ""),
    ("ugly", "negative"),
    ("unhappy", "negative"),
    ("unkempt", ""),
    ("unlucky", ""),
    ("unripe", ""),
    ("unruly", ""),
    ("unselfish", ""),
    ("unsightly", ""),
    ("unsung", ""),
    ("untidy", ""),
    ("untimely", ""),
    ("unwieldy", ""),
    ("upbeat", ""),
    ("upset", ""),
    ("utter", "pure"),
    ("vapid", ""),
    ("wan", ""),
    ("watery", ""),
    ("weary", ""),
    ("wee", ""),
    ("weepy", ""),
    ("weighty", ""),
    ("weird", "negative"),
    ("wiggly", ""),
    ("windy", ""),
    ("wiry", ""),
    ("witty", ""),
    ("wobbly", ""),
    ("woozy", ""),
    ("wordy", ""),
    ("worldly", ""),
    ("wry", ""),
    ("yummy", ""),
    ("zany", ""),
    ("zesty", ""),
]
